def test_argument_checking(self):
    self.assertRaises(TypeError, self.thetype)
    try:
        self.thetype(2)()
    except TypeError:
        pass
    else:
        self.fail('First arg not checked for callability')
