def close(self):
    assert_(0, 'errors.close() must not be called')
