def error(self, exception):
    self._err_handler.error(exception)
