def addFailure(self, test, err):
    unittest.TestResult.addFailure(self, test, err)
    self.failure = err
