def error(self, exception):
    'Handle a recoverable error.'
    raise exception
