def report_unexpected_exception(self, out, test, example, exc_info):
    '\n        Report that the given example raised an unexpected exception.\n        '
    out(((self._failure_header(test, example) + 'Exception raised:\n') + _indent(_exception_traceback(exc_info))))
