def error(self, msg, exc=None):
    self._log(3, ERROR, msg, exc)
