def test_main():
    test_support.run_unittest(TestBug1385040)
