def assertAfterWithManagerInvariantsWithError(self, mock_manager):
    self.assertTrue(mock_manager.enter_called)
    self.assertTrue(mock_manager.exit_called)
    self.assertEqual(mock_manager.exit_args[0], RuntimeError)
    self.assertEqual(mock_manager.exit_args[1], self.TEST_EXCEPTION)
