def error(self, exc):
    self._err_handler.error(_wrap_sax_exception(exc))
