def test_try_except(self):
    hit_except = False
    try:
        raise Exception, 'ahoy!'
    except:
        hit_except = True
    self.assertTrue(hit_except)
