def testBasicErrorOutput(self):

    def non_error_app(e, s):
        s('200 OK', [])
        return []

    def error_app(e, s):
        raise AssertionError('This should be caught by handler')
    h = ErrorHandler()
    h.run(non_error_app)
    self.assertEqual(h.stdout.getvalue(), 'Status: 200 OK\r\nContent-Length: 0\r\n\r\n')
    self.assertEqual(h.stderr.getvalue(), '')
    h = ErrorHandler()
    h.run(error_app)
    self.assertEqual(h.stdout.getvalue(), ('Status: %s\r\nContent-Type: text/plain\r\nContent-Length: %d\r\n\r\n%s' % (h.error_status, len(h.error_body), h.error_body)))
    self.failUnless((h.stderr.getvalue().find('AssertionError') != (-1)))
