def test_raising_custom_attribute_error(self):


    class RaisesCustomMsg(object):

        def __get__(self, instance, type):
            raise AttributeError('Custom message')


    class CustomAttributeError(AttributeError):
        pass


    class RaisesCustomErr(object):

        def __get__(self, instance, type):
            raise CustomAttributeError


    class Foo(object):
        custom_msg = RaisesCustomMsg()
        custom_err = RaisesCustomErr()
    self.assertRaises(CustomAttributeError, (lambda : Foo().custom_err))
    try:
        Foo().custom_msg
        self.assert_(False)
    except AttributeError as e:
        self.assertEquals('Custom message', str(e))
