def handle_error(self):
    (nil, t, v, tbinfo) = compact_traceback()
    try:
        self_repr = repr(self)
    except:
        self_repr = ('<__repr__(self) failed for object at %0x>' % id(self))
    self.log_info(('uncaptured python exception, closing channel %s (%s:%s %s)' % (self_repr, t, v, tbinfo)), 'error')
    self.close()
