def test_exception_in_except_clause(self):

    def f(p):
        (1 / 0)

    def g(p):
        try:
            f(p)
        except:
            try:
                f(p)
            except:
                pass
    f_ident = ident(f)
    g_ident = ident(g)
    self.check_events(g, [(1, 'call', g_ident), (2, 'call', f_ident), (2, 'return', f_ident), (3, 'call', f_ident), (3, 'return', f_ident), (1, 'return', g_ident)])
