def test_ValueError(self):
    self.assertRaises(ValueError, _strptime.strptime, data_string='%d', format='%A')
    for bad_format in ('%', '% ', '%e'):
        try:
            _strptime.strptime('2005', bad_format)
        except ValueError:
            continue
        except Exception as err:
            self.fail(("'%s' raised %s, not ValueError" % (bad_format, err.__class__.__name__)))
        else:
            self.fail(("'%s' did not raise ValueError" % bad_format))
